<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;
use AppBundle\Entity\Image;
use AppBundle\Google\Drive;
use Doctrine\ORM\EntityRepository;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends EntityRepository
{
    public function populateImages(Task $task, Drive $drive)
    {
        $images = $task->getImages();
        $imageUrls = explode("\n", $task->getImageUrls());

        foreach ($imageUrls as $imageUrl) {

            foreach ($images as $image) {
                if ($image->getUrl() == $imageUrl) {
                    continue;
                }
            }

            $image = new Image();
            $image->setUrl($imageUrl);
            $image->setTask($task);
            $image->setFetched(true);
            $image->setContent($drive->getDocumentText($image->getDownloadLink()));

            $this->getEntityManager()->persist($image);
        }

        $this->getEntityManager()->flush();
    }

    public function fetchImageContents(Task $task, Drive $drive)
    {
        $images = $task->getImages();

        /** @var Image $image */
        foreach ($images as $image) {
            $image->setContent($drive->getDocumentText($image->getUrl()));
        }
    }

    public function updateImageContents($fields)
    {
        $fullContent = '';
        $task = null;

        foreach ($fields['image_id'] as $index => $id) {

            $image = $this->find($id);
            $task = $image->getTask();

            $fullContent .= $fields['image_content'][$index];
            $image->setContent($fields['image_content'][$index]);

            $this->getEntityManager()->persist($image);
        }


        $task->setContents($fullContent);
        $this->getEntityManager()->persist($task);

        $this->getEntityManager()->flush();
    }
}
