<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Task;
use AppBundle\Entity\User;
use Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository;

/**
 * TaskRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaskRepository extends EntityRepository
{
    public function lockTask(Task $task, User $user)
    {
        $task->setLockedBy($user);

        $this->getEntityManager()->persist($task);
        $this->getEntityManager()->flush();
    }

    public function getStats()
    {
        $stats = [];

        foreach (['new', 'wip', 'in_review', 'in_approval'] as $state) {
            $stats[$state] = $this->getQueryBuilder()
                ->select('COUNT (o.id)')
                ->where('o.state = :state')
                ->setParameter('state', $state)
                ->getQuery()
                ->getSingleScalarResult();
        }

        return $stats;
    }
}
