sylius_resource:
    resources:
        app.student:
            driver: doctrine/orm
            object_manager: default
            templates: AppBundle:Education
            classes:
                model: AppBundle\Entity\PrimaryEducation
                controller: AppBundle\Controller\PrimaryEducationController
                repository: AppBundle\Repository\PrimaryEducationRepository
        app.patient:
            driver: doctrine/orm
            object_manager: default
            templates: AppBundle:CRUD
            classes:
                model: AppBundle\Entity\Patient
                controller: AppBundle\Controller\PatientController
                repository: AppBundle\Repository\PatientRepository
        app.birth:
            driver: doctrine/orm
            object_manager: default
            templates: AppBundle:Birth
            classes:
                model: AppBundle\Entity\Birth
                controller: AppBundle\Controller\BirthController
                repository: AppBundle\Repository\BirthRepository