sylius_resource:
    resources:
        app.student:
            driver: doctrine/orm
            object_manager: default
            templates: AppBundle:Education
            classes:
                model: AppBundle\Entity\PrimaryEducation
                controller: AppBundle\Controller\PrimaryEducationController
                repository: AppBundle\Repository\PrimaryEducationRepository

#        app.image:
#            driver: doctrine/orm
#            object_manager: default
#            templates: AppBundle:Image
#            classes:
#                model: AppBundle\Entity\Image
#                controller: AppBundle\Controller\ImageController
#                repository: AppBundle\Repository\ImageRepository