### Global Routes ###

dashboard:
    path: /
    methods: [GET]
    defaults:
        _controller: AppBundle:Dashboard:index

translate:
    path: /translate
    methods: [POST]
    defaults:
        _controller: app.controller.birth:translateAction

### Education Resource Routes ###
app_students:
    path: /students
    methods: [GET]
    defaults:
        _controller: app.controller.student:indexAction
        _sylius:
            paginate: 20

app_student_show:
    path: /students/{rowIndex}
    methods: [GET]
    defaults:
        _controller: app.controller.student:showAction
        _sylius:
            repository:
                method: findWithAllRelated
                arguments: [$rowIndex]

### Patient ###
patient_index:
    path: /patients/
    methods: [GET]
    defaults:
        _controller: app.controller.patient:indexAction
        action: show

patient_results:
    path: /patients/results
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: app.controller.patient:resultsAction
        
patient_create:
    path: /patients/new
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: app.controller.patient:createAction
        _sylius:
            form: AppBundle\Form\PatientType
            redirect: patient_index

patient_show:
    path: /patients/view/{id}
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: app.controller.patient:showAction
        _sylius:
            template: AppBundle:Patient:show.html.twig

patient_update:
    path: /patients/edit/{id}
    methods: [GET, PUT]
    options:
        expose: true
    defaults:
        _controller: app.controller.patient:updateAction
        _sylius:
            form: AppBundle\Form\PatientType
            redirect: patient_index

patient_delete:
    path: /patients/delete/{id}
    methods: [DELETE]
    options:
        expose: true
    defaults:
        _controller: app.controller.patient:deleteAction

### Birth ###
birth_index:
    path: /birth/
    methods: [GET]
    defaults:
        _controller: app.controller.birth:indexAction
        action: show

birth_results:
    path: /birth/results
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:resultsAction

birth_events:
    path: /birth/events
    methods: [GET]
    defaults:
        _controller: app.controller.birth:eventsAction

birth_events_results:
    path: /birth/events/results
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:eventResultsAction

birth_create:
    path: /birth/new
    methods: [GET, POST]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:createAction
        _sylius:
            form: AppBundle\Form\BirthType
            template: AppBundle:Birth:create.html.twig
            redirect: patient_index

birth_show:
    path: /birth/view/{id}
    methods: [GET]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:showAction
        _sylius:
            template: AppBundle:Birth:show.html.twig

birth_update:
    path: /birth/edit/{id}
    methods: [GET, PUT]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:updateAction
        _sylius:
            form: AppBundle\Form\BirthRegisterType
            redirect: birth_show

birth_delete:
    path: /birth/delete/{id}
    methods: [DELETE]
    options:
        expose: true
    defaults:
        _controller: app.controller.birth:deleteAction
